development:
  adapter: postgresql
  encoding: unicode
  database: hotel_development

test:
  adapter: postgresql
  encoding: unicode
  database: hotel_test

staging:
  adapter: postgresql
  encoding: unicode
  database: hotel_staging

production:
  adapter: postgresql
  encoding: unicode
  database: hotel_production
